/**
 * Registers the TypeScript loader that Expo uses to require the local config
 * plugin below. Expo reads this file itself, but a plugin it resolves from a
 * path is loaded through plain `require`, which cannot read `.ts` — so without
 * this line `./plugins/with-ui-scene-lifecycle.ts` is simply not found.
 *
 * It must stay above every other import: the loader has to be registered before
 * anything tries to resolve a TypeScript file through it. It is a build-time
 * shim and reaches nothing in the app.
 */
import 'tsx/cjs';

import type { ExpoConfig } from 'expo/config';

/**
 * Everything native about OwnReader is expressed here and generated by
 * `expo prebuild`. `ios/` and `android/` are never committed (ADR 0001): a
 * committed native directory silently stops prebuild from running again, so
 * the `/ios` and `/android` entries in .gitignore are load-bearing, not tidy.
 */

/**
 * ADR 0001, "The deployment target is iOS 17.2, not the platform minimum".
 *
 * Expo SDK 57 will run on 16.4; this is higher on purpose. The CSS Custom
 * Highlight API, which ADR 0005 uses to highlight a word without touching the
 * DOM, arrived in Safari 17.2. Under a 16.4 floor it would need a fallback
 * that wraps each word in an element — the per-word DOM mutation ADR 0005
 * exists to avoid — so the fallback would be a second implementation of the
 * hardest part of the app, written to be worse. Raising the floor deletes that
 * path: ADR 0005 now says in as many words that there is no fallback to write.
 *
 * Lowering this number therefore does not merely widen device support. It
 * reintroduces a rendering path that does not exist.
 */
const IOS_DEPLOYMENT_TARGET = '17.2';

/**
 * The New Architecture is not configured here, and cannot be: SDK 57 removed
 * `newArchEnabled` from the config schema altogether (`@expo/config-types`
 * 57.0.2 has no such key, and no Expo plugin reads one). ADR 0001 says it is
 * mandatory from SDK 55 and there is no opt-out; this is what that looks like
 * in the schema. The only remaining ways to turn it off are React Native's own
 * `RCT_NEW_ARCH_ENABLED` environment variable at pod-install time and a
 * `newArchEnabled` line in `android/gradle.properties` — and `android/` is
 * generated, never committed, so neither can be set here by accident.
 * test/app-config.test.ts fails if the key ever reappears in this file.
 */

const config: ExpoConfig = {
  name: 'OwnReader',
  slug: 'ownreader',
  version: '0.1.0',
  orientation: 'portrait',
  icon: './assets/icon.png',
  userInterfaceStyle: 'automatic',

  ios: {
    supportsTablet: true,
    bundleIdentifier: 'top.xujialiu.ownreader',

    /**
     * ADR 0001's floor, above the platform minimum. Built into the config from
     * SDK 56 — `expo-build-properties`' `ios.deploymentTarget` is deprecated
     * in favour of this key, which is why that plugin is not a dependency.
     */
    deploymentTarget: IOS_DEPLOYMENT_TARGET,

    /**
     * UIBackgroundModes is deliberately NOT written here. The
     * react-native-audio-api plugin below owns it (`iosBackgroundMode: true`
     * appends 'audio'), and two writers of the same key is how it ends up
     * wrong. Verify it in the generated ios/OwnReader/Info.plist after a
     * prebuild, not here.
     */
  },

  android: {
    package: 'top.xujialiu.ownreader',
    adaptiveIcon: {
      backgroundColor: '#E6F4FE',
      foregroundImage: './assets/android-icon-foreground.png',
      backgroundImage: './assets/android-icon-background.png',
      monochromeImage: './assets/android-icon-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
  },

  plugins: [
    /**
     * ADR 0018. Adopts the UIScene life cycle, without which iOS 27 kills the
     * app at launch before any JavaScript runs — every other entry in this list
     * is moot until this one has run. Expo SDK 57.0.24 ships the scene delegate
     * in its own pod and wires it up nowhere; the plugin is three edits to the
     * generated project that do that.
     *
     * It takes no options on purpose. There is one correct way to adopt the
     * scene life cycle and nothing here a reader should be choosing between.
     *
     * Delete this line and the plugin together once Expo's prebuild template
     * adopts the scene life cycle itself. Nothing has to be remembered for that
     * to happen: each of the plugin's three edits asserts that the generated
     * project still looks the way it expects and **fails the prebuild** when it
     * does not, so the day Expo changes the template is the day the build stops
     * and says so. A warning would have been the wrong tool — a prebuild prints
     * hundreds of lines, and the failure being guarded against is a launch-time
     * crash whose entire signal is one symbol name in a crash report.
     */
    './plugins/with-ui-scene-lifecycle.ts',

    [
      'react-native-audio-api',
      {
        /**
         * Adds 'audio' to UIBackgroundModes. Required: the reader synthesizes
         * and plays the next sentence with the screen locked, which is also
         * why the API key is stored at AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY
         * (ADR 0002).
         */
        iosBackgroundMode: true,

        /**
         * Android's half of the same requirement. The plugin also adds
         * FOREGROUND_SERVICE and FOREGROUND_SERVICE_MEDIA_PLAYBACK by
         * default; left at the default rather than restated.
         */
        androidForegroundService: true,
        androidFSTypes: ['mediaPlayback'],

        /**
         * FFmpeg stays in. ADR 0013 asks every provider for raw PCM, but the
         * OpenAI-compatible provider talks to any server speaking that
         * protocol — someone's self-hosted one may only emit encoded audio,
         * and the decode path is the fallback that catches it.
         */
        disableFFmpeg: false,

        /**
         * No microphone. `iosMicrophonePermission` is omitted, so the plugin
         * writes no NSMicrophoneUsageDescription and the app never asks.
         * OwnReader records nothing.
         */
      },
    ],

    [
      'expo-secure-store',
      {
        /**
         * ADR 0002: the Keychain is where a provider's API key lives, at
         * AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY so it can be read during locked
         * background playback.
         *
         * `faceIDPermission: false` follows from that: a key needed at 2 a.m.
         * with the screen locked cannot sit behind a Face ID prompt, so
         * `requireAuthentication` is never used and the plugin's default
         * NSFaceIDUsageDescription would be an unused privacy declaration
         * shipped in the binary. Verified: with this set, the string is absent
         * from the generated Info.plist.
         */
        faceIDPermission: false,
      },
    ],
  ],
};

export default config;
