/**
 * Registers the TypeScript loader that Expo uses to require the local config
 * plugin below. Expo reads this file itself, but a plugin it resolves from a
 * path is loaded through plain `require`, which cannot read `.ts` — so without
 * this line `./plugins/with-ui-scene-lifecycle.ts` is simply not found.
 *
 * It must stay above every other import: the loader has to be registered before
 * anything tries to resolve a TypeScript file through it — and `./app-name`
 * below is one. Expo transpiles this file and only this file; everything the
 * transpiled result requires is resolved by plain Node, so the hoisting is
 * load-bearing for the app's own name as much as for the plugin. It is a
 * build-time shim and reaches nothing in the app.
 */
import 'tsx/cjs';

import type { ExpoConfig } from 'expo/config';

import { APP_NAME } from './app-name';

/**
 * Everything native about OpenReader is expressed here and generated by
 * `expo prebuild`. `ios/` and `android/` are never committed (ADR 0001): a
 * committed native directory silently stops prebuild from running again, so
 * the `/ios` and `/android` entries in .gitignore are load-bearing, not tidy.
 */

/**
 * ADR 0001, "The deployment target is iOS 17.2, not the platform minimum".
 *
 * Expo SDK 57 will run on 16.4; this is higher on purpose. The CSS Custom
 * Highlight API, which ADR 0005 uses to highlight a word without touching the
 * DOM, arrived in Safari 17.2. Under a 16.4 floor it would need a fallback
 * that wraps each word in an element — the per-word DOM mutation ADR 0005
 * exists to avoid — so the fallback would be a second implementation of the
 * hardest part of the app, written to be worse. Raising the floor deletes that
 * path: ADR 0005 now says in as many words that there is no fallback to write.
 *
 * Lowering this number therefore does not merely widen device support. It
 * reintroduces a rendering path that does not exist.
 */
const IOS_DEPLOYMENT_TARGET = '17.2';

/**
 * The New Architecture is not configured here, and cannot be: SDK 57 removed
 * `newArchEnabled` from the config schema altogether (`@expo/config-types`
 * 57.0.2 has no such key, and no Expo plugin reads one). ADR 0001 says it is
 * mandatory from SDK 55 and there is no opt-out; this is what that looks like
 * in the schema. The only remaining ways to turn it off are React Native's own
 * `RCT_NEW_ARCH_ENABLED` environment variable at pod-install time and a
 * `newArchEnabled` line in `android/gradle.properties` — and `android/` is
 * generated, never committed, so neither can be set here by accident.
 * test/app-config.test.ts fails if the key ever reappears in this file.
 */

const config: ExpoConfig = {
  name: APP_NAME,
  slug: 'openreader',
  /**
   * `CFBundleShortVersionString` on iOS and `versionName` on Android. There is
   * no separate iOS short-version key to set — this is it.
   *
   * It stays at the **released** version; the `-beta<n>` each change carries
   * lives in app-version.ts, which Settings shows. Two reasons it cannot live
   * here: Apple takes this key as integers and dots only, and App Store Connect
   * rejects a suffix (ITMS-90060); and it reaches the installed app only
   * through a prebuild, which neither a reload from Metro nor the iPhone build
   * runs, so a beta written here would name a build other than the one running.
   *
   * `package.json` declares the same number, and test/app-config.test.ts fails
   * when the two differ.
   */
  version: '0.0.1',
  orientation: 'portrait',
  /**
   * #83. Everything the icon is lives in `assets/icon/`, and its one source is
   * `OpenReader.icon`, which `ios.icon` below is given whole. This PNG and the
   * Android ones are exported from that document's two layers by
   * `assets/icon/export-android.sh`; after changing a layer, run it and prebuild
   * again. On iOS `ios.icon` overrides this key, so here it is only what an
   * Android launcher too old for adaptive icons shows.
   */
  icon: './assets/icon/icon.png',
  userInterfaceStyle: 'automatic',

  ios: {
    /**
     * #108. iPhone only, the owner's decision for the first release. An iPad
     * runs the iPhone app in compatibility mode, in portrait: the layout that
     * has been tested. With `true`, the iPad app allowed all four orientations
     * (UISupportedInterfaceOrientations~ipad), none of them tested, and App
     * Review tests on iPad.
     */
    supportsTablet: false,
    bundleIdentifier: 'top.xujialiu.openreader',

    /**
     * #108. The paid team. On 2026-09-30 the free Personal Team became it in
     * place and kept this ID. A prebuild writes it as DEVELOPMENT_TEAM, so a
     * fresh ios/ signs without first choosing the team in Xcode.
     */
    appleTeamId: 'UPR29WR8FC',

    /**
     * #108. CFBundleVersion. App Store Connect refuses an upload whose version
     * already has a build with this number or a higher one, so raise it by one
     * before each upload. It reaches the app only through a prebuild. It is a
     * literal rather than computed, so git records which build went up.
     */
    buildNumber: '1',

    config: {
      /**
       * #108. Writes ITSAppUsesNonExemptEncryption = NO. The app's only
       * encryption is HTTPS and WSS through the system, plus the Keychain, and
       * both are exempt. With the key set, no upload waits on the
       * export-compliance question.
       */
      usesNonExemptEncryption: false,
    },

    /**
     * #83. An Icon Composer document rather than PNGs: one file carries the
     * default, dark, clear and tinted appearances and gives the icon Liquid
     * Glass. It has to be this string — Expo's `withIosIcons` warns when a
     * `.icon` is put inside the `{ light, dark, tinted }` object — and its base
     * name, `OpenReader`, becomes ASSETCATALOG_COMPILER_APPICON_NAME.
     *
     * Below iOS 26 the phone shows flat icons Xcode renders from it at build
     * time: `actool` at `--minimum-deployment-target 17.2` wrote light, dark
     * and tintable renditions into Assets.car (notes, 2026-09-29).
     *
     * The dark icon follows the phone's Home Screen icon appearance, never the
     * app's Theme: switching icons with the Theme would take the alternate-icon
     * API, whose every switch shows the owner a system alert.
     */
    icon: './assets/icon/OpenReader.icon',

    /**
     * ADR 0001's floor, above the platform minimum. Built into the config from
     * SDK 56 — `expo-build-properties`' `ios.deploymentTarget` is deprecated
     * in favour of this key, which is why that plugin is not a dependency.
     */
    deploymentTarget: IOS_DEPLOYMENT_TARGET,

    /**
     * UIBackgroundModes is deliberately NOT written here. The
     * react-native-audio-api plugin below owns it (`iosBackgroundMode: true`
     * appends 'audio'), and two writers of the same key is how it ends up
     * wrong. Verify it in the generated ios/OpenReader/Info.plist after a
     * prebuild, not here.
     */
  },

  android: {
    package: 'top.xujialiu.openreader',
    /**
     * #83. Exported from `OpenReader.icon` by `assets/icon/export-android.sh`,
     * the glyph inside the 66 dp circle every launcher mask leaves visible, on
     * the same white as the iOS icon's default fill.
     * Not yet seen on an Android device: the app does not run there (`ink()` in
     * src/app/controls.tsx throws off iOS).
     */
    adaptiveIcon: {
      backgroundColor: '#ffffff',
      foregroundImage: './assets/icon/android-foreground.png',
      monochromeImage: './assets/icon/android-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
  },

  plugins: [
    'expo-sqlite',
    /**
     * ADR 0018. Adopts the UIScene life cycle, without which iOS 27 kills the
     * app at launch before any JavaScript runs — every other entry in this list
     * is moot until this one has run. Expo SDK 57.0.24 ships the scene delegate
     * in its own pod and wires it up nowhere; the plugin is three edits to the
     * generated project that do that.
     *
     * It takes no options on purpose. There is one correct way to adopt the
     * scene life cycle and nothing here a reader should be choosing between.
     *
     * Delete this line and the plugin together once Expo's prebuild template
     * adopts the scene life cycle itself. Nothing has to be remembered for that
     * to happen: each of the plugin's three edits asserts that the generated
     * project still looks the way it expects and **fails the prebuild** when it
     * does not, so the day Expo changes the template is the day the build stops
     * and says so. A warning would have been the wrong tool — a prebuild prints
     * hundreds of lines, and the failure being guarded against is a launch-time
     * crash whose entire signal is one symbol name in a crash report.
     */
    './plugins/with-ui-scene-lifecycle.ts',

    /**
     * ADR 0019. Declares that this app opens EPUBs, which is what puts it in
     * Files' "Open in" and in every share sheet, and asks iOS to hand over the
     * owner's own file rather than copying a 34 MB book into Documents/Inbox on
     * every open.
     *
     * Two Info.plist keys and no options: there is one correct declaration for a
     * type the system already knows, and nothing here a reader should be
     * choosing between. Like the plugin above, each edit **fails the prebuild**
     * if something else has written the key, because the symptom of getting it
     * wrong is the app being absent from a list, which no log line reports.
     */
    './plugins/with-epub-document-types.ts',

    /**
     * ADR 0053. Permits the continued processing task (iOS 26 and later) that a
     * download the owner starts runs under, so that it goes on after the owner
     * leaves the app or locks the phone. One Info.plist key,
     * BGTaskSchedulerPermittedIdentifiers, derived from `ios.bundleIdentifier`
     * above; UIBackgroundModes is left to the audio plugin below. No options,
     * and the prebuild fails if something else writes the key.
     */
    './plugins/with-continued-processing.ts',

    [
      'react-native-audio-api',
      {
        /**
         * Adds 'audio' to UIBackgroundModes. Required: the reader synthesizes
         * and plays the next sentence with the screen locked, which is also
         * why the API key is stored at AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY
         * (ADR 0002).
         */
        iosBackgroundMode: true,

        /**
         * Android's half of the same requirement. The plugin also adds
         * FOREGROUND_SERVICE and FOREGROUND_SERVICE_MEDIA_PLAYBACK by
         * default; left at the default rather than restated.
         */
        androidForegroundService: true,
        androidFSTypes: ['mediaPlayback'],

        /**
         * FFmpeg stays in. ADR 0013 asks every provider for raw PCM, but the
         * OpenAI-compatible provider talks to any server speaking that
         * protocol — someone's self-hosted one may only emit encoded audio,
         * and the decode path is the fallback that catches it.
         */
        disableFFmpeg: false,

        /**
         * #108. OpenReader records nothing and never asks for the microphone.
         * Nothing calls `requestRecordingPermissions`, and the session category
         * is `playback` (src/playback/audio-graph.ts), for which iOS never
         * prompts. The purpose string is required anyway: the library's
         * AudioSessionManager.mm calls `requestRecordPermission`, and App Store
         * Connect rejects a binary that references that API without
         * NSMicrophoneUsageDescription (ITMS-90683), whether or not the app
         * calls it. expo/expo#33761 is the same rejection, from expo-audio.
         */
        iosMicrophonePermission: 'OpenReader does not record audio and does not use the microphone.',
      },
    ],

    [
      'expo-secure-store',
      {
        /**
         * ADR 0002: the Keychain is where a provider's API key lives, at
         * AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY so it can be read during locked
         * background playback.
         *
         * `faceIDPermission: false` follows from that: a key needed at 2 a.m.
         * with the screen locked cannot sit behind a Face ID prompt, so
         * `requireAuthentication` is never used and the plugin's default
         * NSFaceIDUsageDescription would be an unused privacy declaration
         * shipped in the binary. Verified: with this set, the string is absent
         * from the generated Info.plist.
         */
        faceIDPermission: false,
      },
    ],
  ],
};

export default config;
