#!/usr/bin/env python3
"""Write an EPUB whose every Contents row is unreachable (a #151 test need).

Usage: unreachable-contents-fixture.py SOURCE_EPUB OUTPUT_EPUB [TITLE]
Reads SOURCE_EPUB (as generated by ../fixtures/short-test-fixture.ts), rewrites
its EPUB 3 nav so each href points into a folder that is not in the manifest
(`deep/one.xhtml` against the manifest's `one.xhtml`), and retitles the book
(default `Unreachable Contents Test`). The rooted nav join (contents.ts, #125)
then matches nothing, so every Contents row reads `unreachable` and the sheet
draws each at the disabled row's 30 % (#151).

The plain fixture's rows stopped being unreachable when #125 fixed the rooted
nav match; this is the smallest way to get unreachable rows back without
touching fixtures other probes rely on.

Load the output the way any fixture is loaded: copy it into the app's
Documents/Inbox and add it with the harness, `{"seq":N,"do":"add","file":…}`.
"""
import sys
import zipfile


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        raise SystemExit(2)
    src, dst = sys.argv[1], sys.argv[2]
    title = sys.argv[3] if len(sys.argv) > 3 else 'Unreachable Contents Test'
    zin = zipfile.ZipFile(src)
    zout = zipfile.ZipFile(dst, 'w', zipfile.ZIP_DEFLATED)
    for item in zin.infolist():
        data = zin.read(item.filename)
        if item.filename.endswith('.opf'):
            data = data.decode('utf-8').replace(
                'A Short Test of Reading Aloud', title).encode('utf-8')
        if item.filename.endswith('nav.xhtml'):
            text = data.decode('utf-8')
            text = text.replace('href="one.xhtml"', 'href="deep/one.xhtml"')
            text = text.replace('href="two.xhtml"', 'href="deep/two.xhtml"')
            data = text.encode('utf-8')
        zout.writestr(item, data)
    zout.close()
    zin.close()
    print(f'wrote {dst}')


if __name__ == '__main__':
    main()
